@echo off
mkdir "apps"
mkdir "apps\desktop-ui"
mkdir "apps\api-gateway"
mkdir "packages"
mkdir "packages\auth"
mkdir "packages\database"
mkdir "packages\ui-kit"
mkdir "static-archive"
mkdir "static-archive\legacy-sites"
mkdir "static-archive\learning-snippets"
mkdir "static-archive\assignments"
mkdir "scripts"

move /Y "c:\Users\hp\OneDrive\Desktop\web_d\DiscordBot_PhaseParamita" "services\discord-bot"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Sandbox\modules\AnimeNetwork" "static-archive\legacy-sites\anime-network"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Sandbox\modules\WebShowcase" "static-archive\legacy-sites\web-showcase"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\AnimeVerse" "static-archive\legacy-sites\anime-verse"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\HelloAnime" "static-archive\legacy-sites\hello-anime"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\national_daddy_portfolio" "static-archive\legacy-sites\national-portfolio"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\ejs_learning" "static-archive\learning-snippets\ejs_learning"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\express_learning" "static-archive\learning-snippets\express_learning"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\sql_learning" "static-archive\learning-snippets\sql_learning"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\bootstrap_learning" "static-archive\learning-snippets\bootstrap_learning"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Archive\rest_api_learning" "static-archive\learning-snippets\rest_api_learning"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\QuickBuy" "static-archive\assignments\quick-buy"
move /Y "c:\Users\hp\OneDrive\Desktop\web_d\Task_2_KapotaConnect" "static-archive\assignments\kapota-connect"
move /Y "services\user_rest_api" "apps\api-gateway"
